spring:
  main:
    lazy-initialization: true
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driverClassName: @spring.datasource.driverClassName@
  jpa:
    show-sql: @spring.jpa.show-sql@
    properties:
      hibernate:
        dialect:
          @spring.jpa.properties.hibernate.dialect@
    hibernate:
      ddl-auto: @spring.jpa.hibernate.ddl-auto@
  h2:
    console:
      enabled: @spring.h2.console.enabled@
      path: @spring.h2.console.path@
  kafka:
    bootstrap-servers: @spring.kafka.bootstrap-servers@
  rsocket:
    server:
      port: 7000
      transport: websocket
server:
  error:
    include-stacktrace: @server.error.include-stacktrace@